= 3. 安装 {rancher-product-name}
:page-languages: [en, zh]
:revdate: 2026-01-26
:page-revdate: {revdate}


在前文的操作后，你已经有了一个运行的 RKE 集群，现在可以在其中安装 Rancher 了。出于安全考虑，所有到 Rancher 的流量都必须使用 TLS 加密。在本教程中，你将使用 https://cert-manager.io/[cert-manager]自动颁发自签名证书。在实际使用情况下，你可使用 Let's Encrypt 或自己的证书。

== 安装 Helm CLI

include::shared:ROOT:partial$zh/deprecation-helm2.adoc[]

在具有 kubeconfig 的主机上安装 https://helm.sh/docs/intro/install/[Helm] CLI 以访问 Kubernetes 集群：

----
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
chmod +x get_helm.sh
sudo ./get_helm.sh
----

== 安装 cert-manager

向 SUSE Application Collection 进行身份验证：

----
helm registry login dp.apps.rancher.io -u <USERNAME> -p <TOKEN_OR_SECRET>
----

为 cert-manager 创建命名空间：

----
kubectl create namespace cert-manager
----

创建用于从 SUSE Application Collection 拉取镜像的 Secret：

----
kubectl create secret docker-registry application-collection \
  --docker-server=dp.apps.rancher.io \
  --docker-username=<USERNAME> \
  --docker-password=<TOKEN_OR_SECRET> \
  -n cert-manager \
  --dry-run=client -o yaml | kubectl apply -f -
----

从 SUSE Application Collection 安装 cert-manager。请注意,cert-manager 还需要你配置代理,以防它需要与 Let's Encrypt 或其他外部证书颁发商进行通信：

[NOTE]
====

要查看自定义 cert-manager 安装的选项（包括集群使用 PodSecurityPolicies 的情况），请参阅 https://artifacthub.io/packages/helm/cert-manager/cert-manager#configuration[cert-manager 文档]。
====


----
helm upgrade --install cert-manager oci://dp.apps.rancher.io/charts/cert-manager \
  --namespace cert-manager \
  --set crds.enabled=true \
  --set global.imagePullSecrets={application-collection} \
  --set http_proxy=http://${proxy_host} \
  --set https_proxy=http://${proxy_host} \
  --set no_proxy=127.0.0.0/8\\,10.0.0.0/8\\,cattle-system.svc\\,172.16.0.0/12\\,192.168.0.0/16\\,.svc\\,.cluster.local
----

等待 cert-manager 完成启动：

----
kubectl rollout status deployment -n cert-manager cert-manager
kubectl rollout status deployment -n cert-manager cert-manager-webhook
----

== 安装 Rancher Prime

接下来，你可以安装 Rancher Prime 了。首先，添加 Helm 仓库：

----
helm repo add rancher-prime <helm-chart-repo-url>
----

include::shared:ROOT:partial$zh/helm-chart-repo-url.adoc[]

创建命名空间：

----
kubectl create namespace cattle-system
----

然后使用 Helm 安装 Rancher：Rancher 也需要你配置代理，以便它可以与外部应用商店通信，或检索 Kubernetes 版本更新元数据：

----
helm upgrade --install rancher rancher-prime/rancher \
   --namespace cattle-system \
   --set hostname=rancher.example.com \
   --set proxy=http://${proxy_host} \
   --set noProxy=127.0.0.0/8\\,10.0.0.0/8\\,cattle-system.svc\\,172.16.0.0/12\\,192.168.0.0/16\\,.svc\\,.cluster.local
----

等待部署完成：

----
kubectl rollout status deployment -n cattle-system rancher
----

现在，你可以导航到 `+https://rancher.example.com+` 并开始使用 Rancher。

== 其他资源

以下资源可能对安装 Rancher 有帮助：

* xref:installation-and-upgrade/references/helm-chart-options.adoc[Rancher Helm Chart 选项]
* xref:installation-and-upgrade/resources/tls-secrets.adoc[添加 TLS 密文]
* xref:installation-and-upgrade/troubleshooting/troubleshooting.adoc[Rancher Kubernetes 安装的故障排除]
